### ISSUE TITLE
CKeditor plugins repository

### ISSUE THREAD

**Issue by smartcorestudio** [sealocal/ckeditor-bootstrap-tabs#1]
Hi! Seems like it's a very interesting plugin! Why don't you want to publish it in the official CKeditor plugins repository http://ckeditor.com/addons/plugins/ ?

**Comment by sealocal** [comment]
Great! I hope you can find it useful.

Actually, I would like to publish it, but it's just a matter of me spending the time to get it into the repository.  Publishing in this repo was just quicker since I am familiar with GitHub, but not the CKEditor publishing process.

Could you tell me how you found this repo?  Were you looking for something specific and similar to this plugin?

**Comment by smartcorestudio** [comment]
Some time ago I tried to find something similar to this plugin on the official CKEditor site but had no luck. And today I just decided to search for any interesting plugins by keyword "ckeditor" directly on GitHub. I never tried to find CKEditor addons here so I didn't look for something specific today

**Comment by sealocal** [comment]
Thanks for sharing how you found it! That's exactly what I did when I wanted a similar plugin.

This one is now in the addons repository. http://ckeditor.com/addon/bootstrapTabs
