### ISSUE TITLE
bootstrap-dropdown plugin

### ISSUE THREAD

**Issue by chris-ti8m** [sealocal/ckeditor-bootstrap-tabs#14]
Hi Mike,
We saw your ckeditor-bootstrap-tabs plugin and use it successfully in CKeditor. However, we would also need a bootstrap-dropdown integration into CKeditor. Is there something in the pipeline? Or could you give us a hint or hand how to tackle this.

**Comment by sealocal** [comment]
Hi Chris,

I don't have any plans to keep building CKEditor plugins.  I'd say best resource is the CKEditor docs, specifically the how-to's and/or guides they provide for creating a CKEditor plugin.  They basically setup a template for a plugin.  You might want to fork this repo and try replacing the Bootstrap tabs template with the Bootstrap template for a button dropdown.  It might actually be less complicated than this plugin, since Bootstrap can handle multiple button dropdowns on one page.  For this tabs plugin, a little extra effort is taken to maintain uniqueness of sets of tabs on the same page.

**Comment by chris-ti8m** [comment]
Thanks Mike for the response. I took your plugin as a starting point.
